language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: mu9Y8hiHGePAQmXDAwyesu288V1F4911UWJsDnIUMiRQ2tnxHPKu+QQhojsnmCEZqwogDqz9Gxofa648lPHXNvVsZ5PODEUq4pGdoj6oS0yermWA6DeRrIxfdNqNImZWdWdshJ8YQLkbOicKuX1Gp6MoYFBihlnmER7ZwiV33YuZyZEMuuSTzjeGZLA/XiFC/Zu/1y4ZggsR2/JZz47ZfVwbtozakfR871oM52ApthkhwelT8HoQJsXZuodDH9FRMRQaUJXZzmtine9xnNj4g/rFFaXokGkHeakgGOsK8KgXCfoXU1nsnBQGQLVeZkLqQ852KNZlc3giMrm1VeuGjFJjPYxEsTdV2aYS7eqfR87rqhsl8gYZbu5WN19IO1C0g7yrEW8cfEtCAZjyl7TZXmZm8kMTuylD1svkoYQu5dNY2t8u0SpQYS7ijCmFzLapv09U+JKixl6xLJ4V1lYrx+uI8RbUaL9oe1jIujYLDA5V0JYLC6j4O+vPE6sHbqZ7a6UTKX+4FZskzgx438oMDUKdk924GsvlcywZUcW0IbCzS2MO9yiiKbDydTu4L+RkkBvKy403maRo4uSxi0zbNVGkLiU1XrEo3xdGucwfvy1n7FMzh1sJK8gvhP/rJtYlIQ4ajA7eC0Lza4WFhDhXOaMCVRMzSxbKKYu9uOTS078=
  app: blog-mongo-api
  on:
    repo: mikebcbc/mongo-blog-api
